# Generated by Django 4.2.1 on 2023-10-12 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backpack_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='weight_uom',
            field=models.CharField(choices=[('g', 'g'), ('kg', 'kg'), ('lb', 'lb'), ('oz', 'oz')], default='oz', max_length=2),
        ),
    ]
