# Generated by Django 4.2.1 on 2023-05-29 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backpack_list', '0002_item_link_list_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='notes',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
