# Generated by Django 4.2.1 on 2023-05-29 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backpack_list', '0003_alter_list_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='qty',
            field=models.IntegerField(default=1),
        ),
    ]
