# Generated by Django 4.2.1 on 2023-06-07 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backpack_list', '0004_alter_item_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='backpack_list.list'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='backpack_list.category'),
        ),
    ]
